# app/config/security.yml

security:
    encoders:
        NB\UserBundle\Entity\User: sha512

    providers:
        main:
            id: fos_user.user_provider.username
    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_SEATSELLER:    [ROLE_SEATSELLER]
        ROLE_SUPER_ADMIN: [ROLE_SEATSELLER, ROLE_ALLOWED_TO_SWITCH]

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: security_check_route
                success_handler: acme.security.authentication_handler
                failure_handler: acme.security.authentication_handler
                require_previous_session: false
                use_referer : true
                default_target_path: nb_main_dasboard


            logout:
                path:       /logout
                target:     /
            remember_me:
                key:        %secret%
                lifetime:   3650000
                 # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/cookbook/security/access_control.html
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/app, roles: ROLE_SEATSELLER }

