(function(){var n='angularUtils.directives.dirPagination',e='__default',t;try{t=angular.module(n)}catch(u){t=angular.module(n,[])};t.directive('dirPaginate',['$compile','$parse','paginationService',i]).directive('dirPaginateNoCompile',a).directive('dirPaginationControls',['paginationService','paginationTemplate',s]).filter('itemsPerPage',['paginationService',g]).service('paginationService',o).provider('paginationTemplate',c).run(['$templateCache',r]);function i(t,n,i){return{terminal:!0,multiElement:!0,compile:a};function a(a,u){var l=u.dirPaginate,d=l.match(/^\s*([\s\S]+?)\s+in\s+([\s\S]+?)(?:\s+track\s+by\s+([\s\S]+?))?\s*$/),p=/\|\s*itemsPerPage\s*:[^|]*/;if(d[2].match(p)===null){throw'pagination directive: the \'itemsPerPage\' filter must be set.'};var P=d[2].replace(p,''),h=n(P);g(a);var f=u.paginationId||e;i.registerInstance(f);return function(a,g,u){var d=n(u.paginationId)(a)||u.paginationId||e;i.registerInstance(d);var P=r(l,d);s(g,u,P);o(g);var p=t(g),f=c(a,u,d);i.setCurrentPageParser(d,f,a);if(typeof u.totalItems!=='undefined'){i.setAsyncModeTrue(d);a.$watch(function(){return n(u.totalItems)(a)},function(e){if(0<=e){i.setCollectionLength(d,e)}})}
else{a.$watchCollection(function(){return h(a)},function(e){if(e){i.setCollectionLength(d,e.length)}})};p(a)}};function r(t,n){var i,a=!!t.match(/(\|\s*itemsPerPage\s*:[^|]*:[^|]*)/);if(n!==e&&!a){i=t.replace(/(\|\s*itemsPerPage\s*:[^|]*)/,'$1 : \''+n+'\'')}
else{i=t};return i};function s(e,t,n){if(e[0].hasAttribute('dir-paginate-start')||e[0].hasAttribute('data-dir-paginate-start')){t.$set('ngRepeatStart',n);e.eq(e.length-1).attr('ng-repeat-end',!0)}
else{t.$set('ngRepeat',n)}};function g(e){angular.forEach(e,function(e){if(e.nodeType===Node.ELEMENT_NODE){angular.element(e).attr('dir-paginate-no-compile',!0)}})};function o(e){angular.forEach(e,function(e){if(e.nodeType===Node.ELEMENT_NODE){angular.element(e).removeAttr('dir-paginate-no-compile')}});e.eq(0).removeAttr('dir-paginate-start').removeAttr('dir-paginate').removeAttr('data-dir-paginate-start').removeAttr('data-dir-paginate');e.eq(e.length-1).removeAttr('dir-paginate-end').removeAttr('data-dir-paginate-end')};function c(e,t,i){var a;if(t.currentPage){a=n(t.currentPage)}
else{var r=i+'__currentPage';e[r]=1;a=n(r)};return a}};function a(){return{priority:5000,terminal:!0}};function r(e){e.put('angularUtils.directives.dirPagination.template','<div class="pagination" ng-if="1 < pages.length"><a ng-if="boundaryLinks" ng-class="{ disabled : pagination.current == 1 }" class="page" ng-click="setCurrent(1)">First</a><a ng-if="directionLinks" ng-class="{ disabled : pagination.current == 1 }" class="page" ng-click="setCurrent(pagination.current - 1)">Prev</a><a ng-repeat="pageNumber in pages track by $index" ng-class="{ active : pagination.current == pageNumber, disabled : pageNumber == \'...\' }" class="page1" ng-click="setCurrent(pageNumber)">{{ pageNumber }}</a><a ng-if="directionLinks" ng-class="{ disabled : pagination.current == pagination.last }" class="page" ng-click="setCurrent(pagination.current + 1)">Next</a><a ng-if="boundaryLinks"  ng-class="{ disabled : pagination.current == pagination.last }" class="page" ng-click="setCurrent(pagination.last)">Last</a></div>')};function s(t,n){var a=/^\d+$/;return{restrict:'AE',templateUrl:function(e,t){return t.templateUrl||n.getPath()},scope:{maxSize:'=?',onPageChange:'&?',paginationId:'=?'},link:r};function r(n,r,g){var p=g.paginationId||e,s=n.paginationId||g.paginationId||e;if(!t.isRegistered(s)&&!t.isRegistered(p)){var d=(s!==e)?' (id: '+s+') ':' ';throw'pagination directive: the pagination controls'+d+'cannot be used without the corresponding pagination directive.'};if(!n.maxSize){n.maxSize=9};n.directionLinks=angular.isDefined(g.directionLinks)?n.$parent.$eval(g.directionLinks):!0;n.boundaryLinks=angular.isDefined(g.boundaryLinks)?n.$parent.$eval(g.boundaryLinks):!1;var o=Math.max(n.maxSize,5);n.pages=[];n.pagination={last:1,current:1};n.range={lower:1,upper:1,total:1};n.$watch(function(){return(t.getCollectionLength(s)+1)*t.getItemsPerPage(s)},function(e){if(0<e){f()}});n.$watch(function(){return(t.getItemsPerPage(s))},function(e,t){if(e!=t&&typeof t!=='undefined'){c(n.pagination.current)}});n.$watch(function(){return t.getCurrentPage(s)},function(e,t){if(e!=t){c(e)}});n.setCurrent=function(e){if(l(e)){e=parseInt(e,10);t.setCurrentPage(s,e)}};function c(e){if(l(e)){n.pages=i(e,t.getCollectionLength(s),t.getItemsPerPage(s),o);n.pagination.current=e;u();if(n.onPageChange){n.onPageChange({newPageNumber:e})}}};function f(){var e=parseInt(t.getCurrentPage(s))||1;n.pages=i(e,t.getCollectionLength(s),t.getItemsPerPage(s),o);n.pagination.current=e;n.pagination.last=n.pages[n.pages.length-1];if(n.pagination.last<n.pagination.current){n.setCurrent(n.pagination.last)}
else{u()}};function u(){var e=t.getCurrentPage(s),i=t.getItemsPerPage(s),a=t.getCollectionLength(s);n.range.lower=(e-1)*i+1;n.range.upper=Math.min(e*i,a);n.range.total=a};function l(e){return(a.test(e)&&(0<e&&e<=n.pagination.last))}};function i(e,t,n,a){var o=[],g=Math.ceil(t/n),c=Math.ceil(a/2),i;if(e<=c){i='start'}
else if(g-c<e){i='end'}
else{i='middle'};var p=a<g,r=1;while(r<=g&&r<=a){var u=s(r,e,a,g),l=(r===2&&(i==='middle'||i==='end')),d=(r===a-1&&(i==='middle'||i==='start'));if(p&&(l||d)){o.push('...')}
else{o.push(u)};r++};return o};function s(e,t,n,i){var a=Math.ceil(n/2);if(e===n){return i}
else if(e===1){return e}
else if(n<i){if(i-a<t){return i-n+e}
else if(a<t){return t-a+e}
else{return e}}
else{return e}}};function g(t){return function(n,i,a){if(typeof(a)==='undefined'){a=e};if(!t.isRegistered(a)){throw'pagination directive: the itemsPerPage id argument (id: '+a+') does not match a registered pagination-id.'};var s,r;if(n instanceof Array){i=parseInt(i)||9999999999;if(t.isAsyncMode(a)){r=0}
else{r=(t.getCurrentPage(a)-1)*i};s=r+i;t.setItemsPerPage(a,i);return n.slice(r,s)}
else{return n}}};function o(){var e={};var t;this.registerInstance=function(n){if(typeof e[n]==='undefined'){e[n]={asyncMode:!1};t=n}};this.isRegistered=function(t){return(typeof e[t]!=='undefined')};this.getLastInstanceId=function(){return t};this.setCurrentPageParser=function(t,n,i){e[t].currentPageParser=n;e[t].context=i};this.setCurrentPage=function(t,n){e[t].currentPageParser.assign(e[t].context,n)};this.getCurrentPage=function(t){var n=e[t].currentPageParser;return n?n(e[t].context):1};this.setItemsPerPage=function(t,n){e[t].itemsPerPage=n};this.getItemsPerPage=function(t){return e[t].itemsPerPage};this.setCollectionLength=function(t,n){e[t].collectionLength=n};this.getCollectionLength=function(t){return e[t].collectionLength};this.setAsyncModeTrue=function(t){e[t].asyncMode=!0};this.isAsyncMode=function(t){return e[t].asyncMode}};function c(){var e='angularUtils.directives.dirPagination.template';this.setPath=function(t){e=t};this.$get=function(){return{getPath:function(){return e}}}}})();