;$("#searchBtn").on("click",function(e){var r=$(".pickup_datef").val(),s=$("#from").val(),a=$("#to").val(),t=$("#doj").val();window.location.href=base_url+"app/search?from="+s+"&to="+a+"&dateJ="+t});function Login(){if($("#login").parsley().validate()){$(".small_loader").show();var s=$("#login").serializeArray(),a=base_url+"login_check",t=post_ajax(a,s),e=t;$(".small_loader").hide();$(".login_res").show();if(e.success==!1){$(".login_res").html("<p class='error '>"+e.message+"</p>");setTimeout(function(){$(".login_res").hide()},1500)}
else{$(".login_res").html("<p class='success '>"+e.message+"</p>");setTimeout(function(){$(".login_res").hide(),$("#login")[0].reset()},1500);location.reload()}}};function Recharge(){if($("#recharge").parsley().validate()){$(".small_loader").show();var s=$("#recharge").serializeArray(),a=base_url+"app/recharge",t=post_ajax(a,s),e=t;$(".small_loader").hide();$(".recharge_res").show();if(e.success==!1){$(".recharge_res").html("<p class='error '>"+e.message+"</p>");setTimeout(function(){$(".recharge_res").hide()},1500)}
else{$(".recharge_res").html("<p class='success '>"+e.message+"</p>");setTimeout(function(){$(".recharge_res").hide(),$("#recharge")[0].reset()},1500)}}};function SeatSellerBooking(){if($("#booking").parsley().validate()){$(".loader").show();var s=$("#booking").serializeArray(),a=location.target,t=post_ajax(a,s),e=t;$(".loader").hide();$(".recharge_res").show();if(e.success==!1){$(".alert-danger").show();$(".alert-danger").html("<p>"+e.message+"</p>");setTimeout(function(){$(".alert-danger").hide()},1500)}
else{$(".alert-success").show();$(".alert-success").html("<p >"+e.message+"</p>");setTimeout(function(){$(".alert-success").hide(),$("#booking")[0].reset()},1500);window.setTimeout(function(){window.location.href=base_url+"app/confirmed/"+e.booking},5000)}}};function PrintSeatseller(){$(".small_loader").show();var s=$("#print").serializeArray(),a=base_url+"app/print",t=post_ajax(a,s),e=t;$(".small_loader").hide();$(".print_res").show();if(e.success==!1){$(".print_res").html("<p class='error '>"+e.message+"</p>");setTimeout(function(){$(".print_res").hide()},1500)}
else{$(".print_res").html("<p class='success '>"+e.message+"</p>");setTimeout(function(){$(".print_res").hide(),$("#print")[0].reset()},1500);window.setTimeout(function(){window.location.href=base_url+"app/confirmed/"+e.reservation},5000)}};function Signup(){if($("#signup").parsley().validate()){$(".small_loader").show();var s=$("#signup").serializeArray(),a=base_url+"signup",t=post_ajax(a,s),e=t;$(".small_loader").hide();$(".signup_res").show();if(e.status=="failed"){$(".signup_res").html("<p class='error '>"+e.message+"</p>");setTimeout(function(){$(".signup_res").hide()},1500)}
else{$(".signup_res").html("<p class='success '>"+e.message+"</p>");setTimeout(function(){$(".signup_res").hide(),$("#signup")[0].reset()},1500);location.reload()}}};function Forgot(){if($("#forgot").parsley().validate()){$(".small_loader").show();var s=$("#forgot").serializeArray(),a=base_url+"Login/forgot_password",t=post_ajax(a,s),e=JSON.parse(t);$(".small_loader").hide();$(".forgot_res").show();if(e.status=="failed"){$(".forgot_res").show();$(".forgot_res").html("<p class='error '>"+e.message+"</p>");setTimeout(function(){$(".forgot_res").hide()},1500)}
else{$(".forgot_res").show();$(".forgot_res").html("<p class='success '>"+e.message+"</p>");setTimeout(function(){$(".forgot_res").hide(),$("#forgot")[0].reset()},1500)}}};function Confirmation(){if($("#confirmation").parsley().validate()){$(".small_loader").show();var a=$("#confirmation").serializeArray(),t=base_url+"mob-confirm",r=post_ajax(t,a),e=JSON.parse(r);$(".small_loader").hide();$(".forgot_res").show();s;if(e.status=="failed"){$(".forgot_res").html("<p class='error '>"+e.message+"</p>");setTimeout(function(){$(".forgot_res").hide()},1500)}
else{$(".forgot_res").html("<p class='success '>"+e.message+"</p>");setTimeout(function(){$(".forgot_res").hide(),$("#forgot")[0].reset()},1500)}}};function Resetpass(){if($("#reset-pass").parsley().validate()){$(".small_loader").show();var s=$("#reset-pass").serializeArray(),a=base_url+"login/reset_password",t=post_ajax(a,s),e=JSON.parse(t);$(".small_loader").hide();$(".reset_res").show();if(e.status=="failed"){$(".reset_res").html("<p class='error '>"+e.message+"</p>");setTimeout(function(){$(".reset_res").hide()},1500)}
else{$(".reset_res").html("<p class='success '>"+e.message+"</p>");setTimeout(function(){$(".reset_res").hide(),$("#reset-pass")[0].reset()},1500)}}};function Mprint(e){var e=$(e).data("id"),s=window.open(base_url+"payment/new_window/"+e,"","height=800,width=800,scrollbars=yes");if(window.focus){s.focus()}};function Memail(e){$(".loader").show();var e=$(e).data("id"),r={"id":e,"type":"email"};var s=base_url+"payment/email_notification",a=post_ajax(s,r),t=a;$(".loader").hide();if(t.status=="success"){alert("Details has been send your mail")}
else{alert("email")}};function Printticket(){if($("#bookForm").parsley().validate()){$(".loader").show();var e=$("input[name='id']:checked").val(),r=$("#TID").val(),o={"id":r,"type":e};var a=base_url+"printsms",t=post_ajax(a,o);$(".loader").hide();var s=t;if(s.status=="success"){if(e=="email"){$(".result").html("<p class=\"success \">Les details ont été envoyé à votre email.</p>");setTimeout(function(){$(".result").hide()},1500)}
else if(e=="sms"){$(".result").html("<p class=\"success \">Les details ont été envoyé par sms sur votre numéro.</p>");setTimeout(function(){$(".result").hide()},1500);console.log(s.code)}}
else{$(".result").html("<p class=\"error \">Vous avez soit tapé un mauvais numéro de billet ou votre billet n'est pas valide.</p>");setTimeout(function(){$(".result").hide()},1500)}}};function userDetails(){if($("#userForm").parsley().validate()){$(".loader").show();var a=$("#userForm").serializeArray(),s=base_url+"payment/userDetails",t=post_ajax(s,a),e=JSON.parse(t);if(e.status=="success"){$(".item_name_s").val(e.Bookingido);$(".item_names").val(e.uneaqueid);$("#ORDER_ID").val(e.uneaqueid);if(e.BookingidR!="null"){var s="?ido="+e.Bookingido+"&idR="+e.BookingidR}
else{var s="?ido="+e.Bookingido+"&idR="};successurl=base_url+"payment/result"+s;$(".sucess_url").val(successurl);payment=$("#pament_option").val();if(payment=="paypal"){$("#paypals").submit()}
else if(payment=="paytm"){$("#paytmm").submit()}}
else{$(".loader").hide();$("#myModalp").modal("show")}}};function Selectedseat(e){var a=$(e).hasClass("sseater"),t=$(e).hasClass("sseater");if(a!=!0||t!=!0){seat=$(e).data("seat");bus=$(e).data("bus");amount=$(e).data("rate");classs=$(e).data("class");if($(e).hasClass(classs)){$(e).removeClass(classs);if(classs=="seater"){$(e).addClass("selectedseat");$(e).addClass("selecteds")}
else{$(e).addClass("selectedsleeper");$(e).addClass("selecteds")}}
else{$(e).removeClass("selectedseat");$(e).removeClass("selecteds");$(e).removeClass("selectedsleeper");$(e).addClass(classs)};var s=$("#bus"+bus+" .selecteds").map(function(){return $(this).data("seat")}).get();if(s.length>6){alert("A maximum of 6 Seats can be selected");$(e).removeClass("selectedseat");$(e).removeClass("selecteds");$(e).removeClass("selectedsleeper")};var s=$("#bus"+bus+" .selecteds").map(function(){return $(this).data("seat")}).get();$("#bus"+bus+" .seat_no").text(s);$("#bus"+bus+" .seat_nos").val(s);$("#bus"+bus+" .rate_bus").text(amount);$("#bus"+bus+" .total_rate").text(amount*s.length);console.log(("#bus"+bus+" .seat_no"))}};function paypal(){$("#Customerdetails").click()};function post_ajax(e,a){var s="";$.ajax({type:"POST",url:e,data:a,success:function(e){s=e},error:function(e){s="error"},async:!1});return s};