;var App=angular.module('myFrontend',['angularUtils.directives.dirPagination']);App.filter('selectedTags',function(){return function(e,t){return e.filter(function(a){if(t!=''){for(var n in a.singleP){if(t.indexOf(a.singleP[n])!=-1){return!0}};return!1}
else{return e}});return!0}});App.filter('selectedTags1',function(){return function(e,t){return e.filter(function(a){if(t!=''){for(var n in a.amenities){if(t.indexOf(a.amenities[n])!=-1){return!0}};return!1}
else{return e}})}});App.filter('selecteddrop',function(){return function(e,t){return e.filter(function(a){if(t!=''){for(var n in a.singleD){if(t.indexOf(a.singleD[n])!=-1){return!0}};return!1}
else{return e}})}});App.directive('raty',function(){return{restrict:'AE',link:function(e,t,a){e.$evalAsync(function(){$(t).raty({half:!0,start:a.score,number:a.number,starOff:base_url+'assets/images/Star3s.png',starOn:base_url+'assets/images/Star2s.png',readOnly:!0})})}}});App.controller('search',function(e,a,o,i,n,r){$('.loader').show();e.active='false';e.click_service=function(t,a){console.log(t);e.deatails=a;var a=e.deatails.indexOf(t);if(e.deatails[a].active==!0){e.deatails[a].active=!1}
else{e.deatails[a].active=!0};console.log(e.deatails[a].active)};e.selectSeat=function(t,a){e.deatails=t;var n=e.deatails.indexOf(a);if(e.deatails[a].active==!0){e.deatails[a].active=!1}
else{e.deatails[a].active=!0};console.log(e.deatails[a].active)};e.reload=function(e){if($('#myForms').parsley().validate()){window.location.href=base_url+'search/index?from='+e.board_point+'&to='+e.drop_point+'&dateJ='+e.dateJ+'&dateR='+e.dateR}};e.getbusdetails='';function t(e){var o=decodeURIComponent(window.location.search.substring(1)),n=o.split('&'),t,a;for(a=0;a<n.length;a++){t=n[a].split('=');if(t[0]===e){return t[1]===undefined?!0:t[1]}}};e.board_point;e.drop_point;e.getUrlparameter=function(){var r=t('from'),i=t('to'),a=t('dateJ'),s=t('dateR');o({method:'POST',url:base_url+'search/select_bus',data:{'board_point':r,'drop_point':i,'dates':a},headers:{'Content-Type':'application/x-www-form-urlencoded'}}).success(function(t){e.getbusdetails=t;e.board_point=r;e.drop_point=i;e.dateJ=a;e.dateR=s;a=new Date(a);today=new Date();if(today<a){e.datepre='true'}
else{e.datepre='false'};e.date_slide=a.toISOString();if(s!='undefined'){dateRs=new Date(s);e.date_slideR=dateRs.toISOString();if(a<dateRs){e.datenext='false'}
else{e.datenext='true'}}
else{e.datenext='false'};$('.loader').hide()});post_data={'board_point':r,'drop_point':i};link='search/filter_option';var d=n.send_data(link,post_data);d.then(function(t){e.filter=t})};e.Viewseats=function(t,a){post_data={'board_point':e.board_point,'drop_point':e.drop_point,'route_id':a};link='search/select_one_bus';var o=n.send_data(link,post_data);o.then(function(a){e.viewseats=a;var n=e.getbusdetails.indexOf(t);if(e.getbusdetails[n].active==!0){e.getbusdetails[n].active=!1}
else{e.getbusdetails[n].active=!0}})};e.return_date=function(e){if(e!=''){$('#datereturn').val(e);select_bus()}};e.ratingdetails={};e.Ratingdetails=function(t){$('.loader').show();post_data={'bus_id':t};link='search/rating_details';var a=n.send_data(link,post_data);a.then(function(t){e.ratingdetails=t;console.log(t);$('.loader').hide()})};e.odrop='null';e.name='';e.ogrey='';e.Rgrey='Grey';e.Skipreturn=function(){$('.loader').show();var t='undefined';window.location.href=base_url+'payment/index?from='+e.board_point+'&to='+e.drop_point+'&dateJ='+e.dateJ+'&dateR='+t+'&0ckc='+e.oroute_id+'&0nm='+e.lengthss+'&0bpnt='+e.odrop+'&0seats='+e.oseats+'&0bus_id='+e.obus_id+'&Rckc=0&Rnm='+e.lengthss+'&Rbpnt=0&Rseats=0&Rbus_id=0'};e.Continue=function(t,a,n){bus_v=$('#bus'+n+' .seat_nos').val();if(!bus_v){alert('Please select at least 1 seat');return!1};if(t==undefined){alert('Please select your boarding Point');return!1};e.ogrey='';e.Rgrey='Grey';if(e.odrop=='null'){e.odrop=t;e.ogrey='Grey';e.showSkip='true';e.Rgrey='';e.obus_id=n;e.oseats=$('#seat_nos'+n).val();var d=e.oseats;lengtho=d.split(',');var i=lengtho.length;e.lengthss=i;e.oroute_id=a;if(e.dateR!='undefined'){e.returnDetails()}
else{$('.loader').show();window.location.href=base_url+'payment/index?from='+e.board_point+'&to='+e.drop_point+'&dateJ='+e.dateJ+'&dateR='+e.dateR+'&0ckc='+e.oroute_id+'&0nm='+e.lengthss+'&0bpnt='+e.odrop+'&0seats='+e.oseats+'&0bus_id='+e.obus_id+'&Rckc=0&Rnm='+i+'&Rbpnt=0&Rseats=0&Rbus_id=0'}}
else{var o=$('#seat_nos'+n).val(),s=o.split(','),r=s.length;if(e.lengthss!=r){alert('A maximum of '+e.lengthss+' Seats can be selected as in the onward journey ');return!1};$('.loader').show();window.location.href=base_url+'payment/index?from='+e.board_point+'&to='+e.drop_point+'&dateJ='+e.dateJ+'&dateR='+e.dateR+'&0ckc='+e.oroute_id+'&0nm='+e.oseats.length+'&0bpnt='+e.odrop+'&0seats='+e.oseats+'&Rckc='+a+'&Rnm='+r+'&Rbpnt='+t+'&Rseats='+o+'&Rbus_id='+n}};e.returnDetails=function(){var i=t('from'),s=t('to'),a=t('dateJ'),r=t('dateR');o({method:'POST',url:base_url+'search/select_bus',data:{'board_point':s,'drop_point':i,'dates':r},headers:{'Content-Type':'application/x-www-form-urlencoded'}}).success(function(t){e.getbusdetails=t;e.board_point=i;e.drop_point=s;e.dateJ=a;e.dateR=r;a=new Date(a);e.date_slide=a.toISOString();if(r!='undefined'){dateRs=new Date(r);e.date_slideR=dateRs.toISOString()};$('.loader').hide()});post_data={'board_point':s,'drop_point':i};link='search/filter_option';var d=n.send_data(link,post_data);d.then(function(t){e.filter=t})};e.Twowaypaymentdetails='';e.getUrlparameterPayment=function(){$('.loader').show();var d=t('from'),l=t('to'),n=t('dateJ'),a=t('dateR'),u=t('Rnm'),r=t('0ckc'),i=t('0bpnt'),c=t('0seats'),o=t('Rckc'),s=t('Rbpnt'),f=t('Rseats');e.paymentReturnOneway(r,i);if(o!=0){e.paymentReturnOneway2(o,s)};e.board_points=d;e.drop_points=l;e.oboard_id=i;e.oroute_id=r;e.oseat_no=c;e.Rboard_id=s;e.Rroute_id=o;e.Rseat_no=f;e.counter=Array;e.numberss=parseInt(u);n=new Date(n);e.dateR=a;e.dates=n.toISOString();if(a!='undefined'){a=new Date(a);e.Returndates=a.toISOString()}};e.sums='null';e.TotalAmount=function(t){if(e.sums=='null'){e.sums=t;e.totals=parseInt(e.sums)}
else{e.totals=parseInt(e.sums)+parseInt(t)};$('.loader').hide()};e.paymentReturnOneway=function(t,a){post_data={'route_id':t,'boarding_point_id':a};link='search/select_one_bus';var r='',o=n.send_data(link,post_data);o.then(function(t){e.Onewaypaymentdetails=t;e.paypaldetails=t.paypals;e.TotalAmount(e.Onewaypaymentdetails[0].fare*e.numberss)})};e.paymentReturnOneway2=function(t,a){post_data={'route_id':t,'boarding_point_id':a};link='search/select_one_bus';var r='',o=n.send_data(link,post_data);o.then(function(t){e.Twowaypaymentdetails=t;e.TotalAmount(e.Twowaypaymentdetails[0].fare*e.numberss)})};e.SubmitFunction=function(t){var a=angular.element(t.target);a.attr('action',e.paypaldetails.paypal);a.submit()};e.item={};e.forms={};e.userDetails=function(t){if($('#userForm').parsley().validate()){console.log(e.forms);return!1}};e.getNumber=function(e){console.log(new Array(e));return new Array(e)};e.hiddenDiv=[];e.showDiv=function(t){e.hiddenDiv[t]=!e.hiddenDiv[t]};e.timediff=function(e,t){return moment.utc(moment(t).diff(moment(e))).format('mm')};e.previous=function(a){var i=t('from'),s=t('to'),d=t('dateR'),n=new Date(a),l=new Date(n),u=new Date();if(u<=n){e.date_slide=l.setDate(n.getDate()-1);var o=r('date')(e.date_slide,'MM/dd/yyyy');window.location.href=base_url+'search/index?from='+i+'&to='+s+'&dateJ='+o+'&dateR='+d}};e.next=function(a){var s=t('from'),d=t('to'),n=new Date(a),o=t('dateR'),l=new Date(n);if(o!='undefined'){var u=new Date(o);if(u>n){e.date_slide=l.setDate(n.getDate()+1);var i=r('date')(e.date_slide,'MM/dd/yyyy');window.location.href=base_url+'search/index?from='+s+'&to='+d+'&dateJ='+i+'&dateR='+o}}
else{e.date_slide=l.setDate(n.getDate()+1);var i=r('date')(e.date_slide,'MM/dd/yyyy');window.location.href=base_url+'search/index?from='+s+'&to='+d+'&dateJ='+i+'&dateR='+o}};e.colourIncludes=[];e.colourIncludes1=[];e.tags=[];e.amt=[];e.drop=[];e.rates=[];e.includedrop=function(t){var a=$.inArray(t,e.drop);if(a>-1){e.drop.splice(a,1)}
else{e.drop.push(t)}};e.includeBus3=function(t){console.log(t);console.log(e.amt);var a=$.inArray(t,e.amt);if(a>-1){e.amt.splice(a,1)}
else{e.amt.push(t)}};e.includeBus=function(t){var a=$.inArray(t,e.colourIncludes);if(a>-1){e.colourIncludes.splice(a,1);console.log(e.colourIncludes)}
else{e.colourIncludes.push(t);console.log(e.colourIncludes)}};e.includeBus1=function(t){var a=$.inArray(t,e.colourIncludes1);if(a>-1){e.colourIncludes1.splice(a,1)}
else{e.colourIncludes1.push(t)}};e.includeBus2=function(t){var a=$.inArray(t,e.tags);if(a>-1){e.tags.splice(a,1)}
else{e.tags.push(t)}};e.rated=function(t){angular.forEach(e.getbusdetails,function(a,n){if(a.AvgPrice!=null){if(a.AvgPrice>t){var o=$.inArray(a.AvgPrice,e.rates);if(o>-1){e.rates.splice(o,1)}
else{e.rates.push(a.AvgPrice)}}}})};e.ratingFilter1=function(t){if(e.rates.length>0){if($.inArray(t.AvgPrice,e.rates)<0)return};return t};e.colourFilter=function(t){if(e.colourIncludes.length>0){if($.inArray(t.bus_name,e.colourIncludes)<0)return};return t};e.colourFilter1=function(t){if(e.colourIncludes1.length>0){if($.inArray(t.bus_type,e.colourIncludes1)<0)return};return t};e.getTripdetails=function(){$('.loader').show();post_data='';link='Myaccount/get_tripdetails';var t=n.send_data(link,post_data);t.then(function(t){e.tripDetails=t;$('.loader').hide()})};e.isDate=function(t){e.myDate=r('date')(new Date(),'hh:mm:a');e.today=t;if(e.myDate>e.today){console.log(e.myDate);return!0}
else{console.log(e.myDate);return!1}};e.Cancel=function(e){post_data={'id':e};link='Myaccount/cancel';var t=n.send_data(link,post_data);t.then(function(e){alert(e)})};e.rating=function(){post_data='';link='Myaccount/rating';var e=n.send_data(link,post_data);e.then(function(e){alert(e)})}});