/*!
 * jQuery Form Plugin
 * version: 3.51.0-2014.06.20
 * Requires jQuery v1.5 or later
 * Copyright (c) 2014 M. Alsup
 * Examples and documentation at: http://malsup.com/jquery/form/
 * Project repository: https://github.com/malsup/form
 * Dual licensed under the MIT and GPL licenses.
 * https://github.com/malsup/form#copyright-and-license
 */
(function(e){'use strict';if(typeof define==='function'&&define.amd){define(['jquery'],e)}
else{e((typeof(jQuery)!='undefined')?jQuery:window.Zepto)}}(function(e){'use strict';var r={};r.fileapi=e('<input type=\'file\'/>').get(0).files!==undefined;r.formdata=window.FormData!==undefined;var n=!!e.fn.prop;e.fn.attr2=function(){if(!n){return this.attr.apply(this,arguments)};var e=this.prop.apply(this,arguments);if((e&&e.jquery)||typeof e==='string'){return e};return this.attr.apply(this,arguments)};e.fn.ajaxSubmit=function(a){if(!this.length){t('ajaxSubmit: skipping submit process - no element selected');return this};var o,x,s,i=this;if(typeof a=='function'){a={success:a}}
else if(a===undefined){a={}};o=a.type||this.attr2('method');x=a.url||this.attr2('action');s=(typeof x==='string')?e.trim(x):'';s=s||window.location.href||'';if(s){s=(s.match(/^([^#]+)/)||[])[1]};a=e.extend(!0,{url:s,success:e.ajaxSettings.success,type:o||e.ajaxSettings.type,iframeSrc:/^https/i.test(window.location.href||'')?'javascript:false':'about:blank'},a);var h={};this.trigger('form-pre-serialize',[this,a,h]);if(h.veto){t('ajaxSubmit: submit vetoed via form-pre-serialize trigger');return this};if(a.beforeSerialize&&a.beforeSerialize(this,a)===!1){t('ajaxSubmit: submit aborted via beforeSerialize callback');return this};var p=a.traditional;if(p===undefined){p=e.ajaxSettings.traditional};var d=[],m,u=this.formToArray(a.semantic,d);if(a.data){a.extraData=a.data;m=e.param(a.data,p)};if(a.beforeSubmit&&a.beforeSubmit(u,this,a)===!1){t('ajaxSubmit: submit aborted via beforeSubmit callback');return this};this.trigger('form-submit-validate',[u,this,a,h]);if(h.veto){t('ajaxSubmit: submit vetoed via form-submit-validate trigger');return this};var c=e.param(u,p);if(m){c=(c?(c+'&'+m):m)};if(a.type.toUpperCase()=='GET'){a.url+=(a.url.indexOf('?')>=0?'&':'?')+c;a.data=null}
else{a.data=c};var f=[];if(a.resetForm){f.push(function(){i.resetForm()})};if(a.clearForm){f.push(function(){i.clearForm(a.includeHidden)})};if(!a.dataType&&a.target){var A=a.success||function(){};f.push(function(t){var r=a.replaceTarget?'replaceWith':'html';e(a.target)[r](t).each(A,arguments)})}
else if(a.success){f.push(a.success)};a.success=function(e,t,r){var s=a.context||this;for(var n=0,o=f.length;n<o;n++){f[n].apply(s,[e,t,r||i,i])}};if(a.error){var k=a.error;a.error=function(e,t,r){var n=a.context||this;k.apply(n,[e,t,r,i])}};if(a.complete){var D=a.complete;a.complete=function(e,t){var r=a.context||this;D.apply(r,[e,t,i])}};var S=e('input[type=file]:enabled',this).filter(function(){return e(this).val()!==''}),y=S.length>0,b='multipart/form-data',T=(i.attr('enctype')==b||i.attr('encoding')==b),g=r.fileapi&&r.formdata;t('fileAPI :'+g);var w=(y||T)&&!g,l;if(a.iframe!==!1&&(a.iframe||w)){if(a.closeKeepAlive){e.get(a.closeKeepAlive,function(){l=j(u)})}
else{l=j(u)}}
else if((y||T)&&g){l=E(u)}
else{l=e.ajax(a)};i.removeData('jqxhr').data('jqxhr',l);for(var v=0;v<d.length;v++){d[v]=null};this.trigger('form-submit-notify',[this,a]);return this;function L(t){var i=e.param(t,a.traditional).split('&'),s=i.length,o=[],r,n;for(r=0;r<s;r++){i[r]=i[r].replace(/\+/g,' ');n=i[r].split('=');o.push([decodeURIComponent(n[0]),decodeURIComponent(n[1])])};return o};function E(t){var s=new FormData();for(var r=0;r<t.length;r++){s.append(t[r].name,t[r].value)};if(a.extraData){var n=L(a.extraData);for(r=0;r<n.length;r++){if(n[r]){s.append(n[r][0],n[r][1])}}};a.data=null;var i=e.extend(!0,{},e.ajaxSettings,a,{contentType:!1,processData:!1,cache:!1,type:o||'POST'});if(a.uploadProgress){i.xhr=function(){var t=e.ajaxSettings.xhr();if(t.upload){t.upload.addEventListener('progress',function(e){var t=0,r=e.loaded||e.position,i=e.total;if(e.lengthComputable){t=Math.ceil(r/i*100)};a.uploadProgress(e,r,i,t)},!1)};return t}};i.data=null;var f=i.beforeSend;i.beforeSend=function(e,t){if(a.formData){t.data=a.formData}
else{t.data=s};if(f){f.call(this,e,t)}};return e.ajax(i)};function j(f){var l=i[0],w,T,r,h,y,m,c,s,x,v,S,b,p=e.Deferred();p.abort=function(e){s.abort(e)};if(f){for(T=0;T<d.length;T++){w=e(d[T]);if(n){w.prop('disabled',!1)}
else{w.removeAttr('disabled')}}};r=e.extend(!0,{},e.ajaxSettings,a);r.context=r.context||r;y='jqFormIO'+(new Date().getTime());if(r.iframeTarget){m=e(r.iframeTarget);v=m.attr2('name');if(!v){m.attr2('name',y)}
else{y=v}}
else{m=e('<iframe name="'+y+'" src="'+r.iframeSrc+'" />');m.css({position:'absolute',top:'-1000px',left:'-1000px'})};c=m[0];s={aborted:0,responseText:null,responseXML:null,status:0,statusText:'n/a',getAllResponseHeaders:function(){},getResponseHeader:function(){},setRequestHeader:function(){},abort:function(a){var n=(a==='timeout'?'timeout':'aborted');t('aborting upload... '+n);this.aborted=1;try{if(c.contentWindow.document.execCommand){c.contentWindow.document.execCommand('Stop')}}catch(i){};m.attr('src',r.iframeSrc);s.error=n;if(r.error){r.error.call(r.context,s,n,a)};if(h){e.event.trigger('ajaxError',[s,r,n])};if(r.complete){r.complete.call(r.context,s,n)}}};h=r.global;if(h&&0===e.active++){e.event.trigger('ajaxStart')};if(h){e.event.trigger('ajaxSend',[s,r])};if(r.beforeSend&&r.beforeSend.call(r.context,s,r)===!1){if(r.global){e.active--};p.reject();return p};if(s.aborted){p.reject();return p};x=l.clk;if(x){v=x.name;if(v&&!x.disabled){r.extraData=r.extraData||{};r.extraData[v]=x.value;if(x.type=='image'){r.extraData[v+'.x']=l.clk_x;r.extraData[v+'.y']=l.clk_y}}};var E=1,j=2;function M(e){var a=null;try{if(e.contentWindow){a=e.contentWindow.document}}catch(r){t('cannot get iframe.contentWindow document: '+r)};if(a){return a};try{a=e.contentDocument?e.contentDocument:e.document}catch(r){t('cannot get iframe.contentDocument: '+r);a=e.document};return a};var A=e('meta[name=csrf-token]').attr('content'),L=e('meta[name=csrf-param]').attr('content');if(L&&A){r.extraData=r.extraData||{};r.extraData[L]=A};function F(){var f=i.attr2('target'),u=i.attr2('action'),h='multipart/form-data',v=i.attr('enctype')||i.attr('encoding')||h;l.setAttribute('target',y);if(!o||/post/i.test(o)){l.setAttribute('method','POST')};if(u!=r.url){l.setAttribute('action',r.url)};if(!r.skipEncodingOverride&&(!o||/post/i.test(o))){i.attr({encoding:'multipart/form-data',enctype:'multipart/form-data'})};if(r.timeout){b=setTimeout(function(){S=!0;g(E)},r.timeout)};function d(){try{var r=M(c).readyState;t('state = '+r);if(r&&r.toLowerCase()=='uninitialized'){setTimeout(d,50)}}catch(e){t('Server abort: ',e,' (',e.name,')');g(j);if(b){clearTimeout(b)};b=undefined}};var s=[];try{if(r.extraData){for(var a in r.extraData){if(r.extraData.hasOwnProperty(a)){if(e.isPlainObject(r.extraData[a])&&r.extraData[a].hasOwnProperty('name')&&r.extraData[a].hasOwnProperty('value')){s.push(e('<input type="hidden" name="'+r.extraData[a].name+'">').val(r.extraData[a].value).appendTo(l)[0])}
else{s.push(e('<input type="hidden" name="'+a+'">').val(r.extraData[a]).appendTo(l)[0])}}}};if(!r.iframeTarget){m.appendTo('body')};if(c.attachEvent){c.attachEvent('onload',g)}
else{c.addEventListener('load',g,!1)};setTimeout(d,15);try{l.submit()}catch(n){var p=document.createElement('form').submit;p.apply(l)}}finally{l.setAttribute('action',u);l.setAttribute('enctype',v);if(f){l.setAttribute('target',f)}
else{i.removeAttr('target')};e(s).remove()}};if(r.forceSync){F()}
else{setTimeout(F,10)};var D,u,N=50,k;function g(a){if(s.aborted||k){return};u=M(c);if(!u){t('cannot access response document');a=j};if(a===E&&s){s.abort('timeout');p.reject(s,'timeout');return}
else if(a==j&&s){s.abort('server abort');p.reject(s,'error','server abort');return};if(!u||u.location.href==r.iframeSrc){if(!S){return}};if(c.detachEvent){c.detachEvent('onload',g)}
else{c.removeEventListener('load',g,!1)};var i='success',o;try{if(S){throw'timeout'};var y=r.dataType=='xml'||u.XMLDocument||e.isXMLDoc(u);t('isXml='+y);if(!y&&window.opera&&(u.body===null||!u.body.innerHTML)){if(--N){t('requeing onLoad callback, DOM not available');setTimeout(g,250);return}};var f=u.body?u.body:u.documentElement;s.responseText=f?f.innerHTML:null;s.responseXML=u.XMLDocument?u.XMLDocument:u;if(y){r.dataType='xml'};s.getResponseHeader=function(e){var t={'content-type':r.dataType};return t[e.toLowerCase()]};if(f){s.status=Number(f.getAttribute('status'))||s.status;s.statusText=f.getAttribute('statusText')||s.statusText};var x=(r.dataType||'').toLowerCase(),T=/(json|script|text)/.test(x);if(T||r.textarea){var v=u.getElementsByTagName('textarea')[0];if(v){s.responseText=v.value;s.status=Number(v.getAttribute('status'))||s.status;s.statusText=v.getAttribute('statusText')||s.statusText}
else if(T){var l=u.getElementsByTagName('pre')[0],d=u.getElementsByTagName('body')[0];if(l){s.responseText=l.textContent?l.textContent:l.innerText}
else if(d){s.responseText=d.textContent?d.textContent:d.innerText}}}
else if(x=='xml'&&!s.responseXML&&s.responseText){s.responseXML=O(s.responseText)};try{D=C(s,x,r)}catch(n){i='parsererror';s.error=o=(n||i)}}catch(n){t('error caught: ',n);i='error';s.error=o=(n||i)};if(s.aborted){t('upload aborted');i=null};if(s.status){i=(s.status>=200&&s.status<300||s.status===304)?'success':'error'};if(i==='success'){if(r.success){r.success.call(r.context,D,'success',s)};p.resolve(s.responseText,'success',s);if(h){e.event.trigger('ajaxSuccess',[s,r])}}
else if(i){if(o===undefined){o=s.statusText};if(r.error){r.error.call(r.context,s,i,o)};p.reject(s,'error',o);if(h){e.event.trigger('ajaxError',[s,r,o])}};if(h){e.event.trigger('ajaxComplete',[s,r])};if(h&&!--e.active){e.event.trigger('ajaxStop')};if(r.complete){r.complete.call(r.context,s,i)};k=!0;if(r.timeout){clearTimeout(b)};setTimeout(function(){if(!r.iframeTarget){m.remove()}
else{m.attr('src',r.iframeSrc)};s.responseXML=null},100)};var O=e.parseXML||function(e,t){if(window.ActiveXObject){t=new ActiveXObject('Microsoft.XMLDOM');t.async='false';t.loadXML(e)}
else{t=(new DOMParser()).parseFromString(e,'text/xml')};return(t&&t.documentElement&&t.documentElement.nodeName!='parsererror')?t:null},X=e.parseJSON||function(e){return window['eval']('('+e+')')},C=function(t,r,i){var n=t.getResponseHeader('content-type')||'',o=r==='xml'||!r&&n.indexOf('xml')>=0,a=o?t.responseXML:t.responseText;if(o&&a.documentElement.nodeName==='parsererror'){if(e.error){e.error('parsererror')}};if(i&&i.dataFilter){a=i.dataFilter(a,r)};if(typeof a==='string'){if(r==='json'||!r&&n.indexOf('json')>=0){a=X(a)}
else if(r==='script'||!r&&n.indexOf('javascript')>=0){e.globalEval(a)}};return a};return p}};e.fn.ajaxForm=function(r){r=r||{};r.delegation=r.delegation&&e.isFunction(e.fn.on);if(!r.delegation&&this.length===0){var n={s:this.selector,c:this.context};if(!e.isReady&&n.s){t('DOM not ready, queuing ajaxForm');e(function(){e(n.s,n.c).ajaxForm(r)});return this};t('terminating; zero elements found by selector'+(e.isReady?'':' (DOM not ready)'));return this};if(r.delegation){e(document).off('submit.form-plugin',this.selector,a).off('click.form-plugin',this.selector,i).on('submit.form-plugin',this.selector,r,a).on('click.form-plugin',this.selector,r,i);return this};return this.ajaxFormUnbind().bind('submit.form-plugin',r,a).bind('click.form-plugin',r,i)};function a(t){var r=t.data;if(!t.isDefaultPrevented()){t.preventDefault();e(t.target).ajaxSubmit(r)}};function i(t){var a=t.target,i=e(a);if(!(i.is('[type=submit],[type=image]'))){var o=i.closest('[type=submit]');if(o.length===0){return};a=o[0]};var r=this;r.clk=a;if(a.type=='image'){if(t.offsetX!==undefined){r.clk_x=t.offsetX;r.clk_y=t.offsetY}
else if(typeof e.fn.offset=='function'){var n=i.offset();r.clk_x=t.pageX-n.left;r.clk_y=t.pageY-n.top}
else{r.clk_x=t.pageX-a.offsetLeft;r.clk_y=t.pageY-a.offsetTop}};setTimeout(function(){r.clk=r.clk_x=r.clk_y=null},100)};e.fn.ajaxFormUnbind=function(){return this.unbind('submit.form-plugin click.form-plugin')};e.fn.formToArray=function(t,n){var o=[];if(this.length===0){return o};var s=this[0],x=this.attr('id'),f=t?s.getElementsByTagName('*'):s.elements,p;if(f&&!/MSIE [678]/.test(navigator.userAgent)){f=e(f).get()};if(x){p=e(':input[form="'+x+'"]').get();if(p.length){f=(f||[]).concat(p)}};if(!f||!f.length){return o};var c,u,i,l,a,v,g;for(c=0,v=f.length;c<v;c++){a=f[c];i=a.name;if(!i||a.disabled){continue};if(t&&s.clk&&a.type=='image'){if(s.clk==a){o.push({name:i,value:e(a).val(),type:a.type});o.push({name:i+'.x',value:s.clk_x},{name:i+'.y',value:s.clk_y})};continue};l=e.fieldValue(a,!0);if(l&&l.constructor==Array){if(n){n.push(a)};for(u=0,g=l.length;u<g;u++){o.push({name:i,value:l[u]})}}
else if(r.fileapi&&a.type=='file'){if(n){n.push(a)};var m=a.files;if(m.length){for(u=0;u<m.length;u++){o.push({name:i,value:m[u],type:a.type})}}
else{o.push({name:i,value:'',type:a.type})}}
else if(l!==null&&typeof l!='undefined'){if(n){n.push(a)};o.push({name:i,value:l,type:a.type,required:a.required})}};if(!t&&s.clk){var h=e(s.clk),d=h[0];i=d.name;if(i&&!d.disabled&&d.type=='image'){o.push({name:i,value:h.val()});o.push({name:i+'.x',value:s.clk_x},{name:i+'.y',value:s.clk_y})}};return o};e.fn.formSerialize=function(t){return e.param(this.formToArray(t))};e.fn.fieldSerialize=function(t){var r=[];this.each(function(){var n=this.name;if(!n){return};var a=e.fieldValue(this,t);if(a&&a.constructor==Array){for(var i=0,o=a.length;i<o;i++){r.push({name:n,value:a[i]})}}
else if(a!==null&&typeof a!='undefined'){r.push({name:this.name,value:a})}});return e.param(r)};e.fn.fieldValue=function(t){for(var a=[],i=0,o=this.length;i<o;i++){var n=this[i],r=e.fieldValue(n,t);if(r===null||typeof r=='undefined'||(r.constructor==Array&&!r.length)){continue};if(r.constructor==Array){e.merge(a,r)}
else{a.push(r)}};return a};e.fieldValue=function(t,r){var m=t.name,i=t.type,c=t.tagName.toLowerCase();if(r===undefined){r=!0};if(r&&(!m||t.disabled||i=='reset'||i=='button'||(i=='checkbox'||i=='radio')&&!t.checked||(i=='submit'||i=='image')&&t.form&&t.form.clk!=t||c=='select'&&t.selectedIndex==-1)){return null};if(c=='select'){var f=t.selectedIndex;if(f<0){return null};var u=[],l=t.options,s=(i=='select-one'),d=(s?f+1:l.length);for(var o=(s?f:0);o<d;o++){var a=l[o];if(a.selected){var n=a.value;if(!n){n=(a.attributes&&a.attributes.value&&!(a.attributes.value.specified))?a.text:a.value};if(s){return n};u.push(n)}};return u};return e(t).val()};e.fn.clearForm=function(t){return this.each(function(){e('input,select,textarea',this).clearFields(t)})};e.fn.clearFields=e.fn.clearInputs=function(t){var r=/^(?:color|date|datetime|email|month|number|password|range|search|tel|text|time|url|week)$/i;return this.each(function(){var a=this.type,i=this.tagName.toLowerCase();if(r.test(a)||i=='textarea'){this.value=''}
else if(a=='checkbox'||a=='radio'){this.checked=!1}
else if(i=='select'){this.selectedIndex=-1}
else if(a=='file'){if(/MSIE/.test(navigator.userAgent)){e(this).replaceWith(e(this).clone(!0))}
else{e(this).val('')}}
else if(t){if((t===!0&&/hidden/.test(a))||(typeof t=='string'&&e(this).is(t))){this.value=''}}})};e.fn.resetForm=function(){return this.each(function(){if(typeof this.reset=='function'||(typeof this.reset=='object'&&!this.reset.nodeType)){this.reset()}})};e.fn.enable=function(e){if(e===undefined){e=!0};return this.each(function(){this.disabled=!e})};e.fn.selected=function(t){if(t===undefined){t=!0};return this.each(function(){var a=this.type;if(a=='checkbox'||a=='radio'){this.checked=t}
else if(this.tagName.toLowerCase()=='option'){var r=e(this).parent('select');if(t&&r[0]&&r[0].type=='select-one'){r.find('option').selected(!1)};this.selected=t}})};e.fn.ajaxSubmit.debug=!1;function t(){if(!e.fn.ajaxSubmit.debug){return};var t='[jquery.form] '+Array.prototype.join.call(arguments,'');if(window.console&&window.console.log){window.console.log(t)}
else if(window.opera&&window.opera.postError){window.opera.postError(t)}}}));