<?php

namespace NB\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function isCredentialsExists($email, $mob){
        $queryBuilder = $this
            ->createQueryBuilder('u')
            ->where('u.email =:email')
            ->orWhere('u.mob =:mob')
            ->setParameters(array('email'=> $email, 'mob' => $mob));
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();
        //$results = $results;

        if($results != null)
            return true;
        else
            return false;



    }
}
