<?php

namespace NB\MainBundle\Repository;

/**
 * IncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStatus($users){
        $queryBuilder = $this
            ->createQueryBuilder('i')
            ->innerJoin('i.users', 'u')
            ->select('SUM(i.montant) As solde')
            ->where('u.id = :users')
            ->setParameter('users', $users);
        // On récupère la Query à partir du QueryBuilder
        $query = $queryBuilder->getQuery();
        // On récupère les résultats à partir de la Query
        $results = $query->getResult();

      // var_dump($results[0]); exit;
        $outcome = $this->_em->getRepository('NBMainBundle:Outcome')->getSolde($users);

        $total = $results[0]['solde'] - $outcome[0]['solde'];

        return $total;

    }

    public function getHistory($users, $from = null, $to = null){
        if($from == null && $to == null){
            $queryBuilder = $this
                ->createQueryBuilder('i')
                ->innerJoin('i.users', 'u')
                ->where('u.id = :users')
                ->setParameter('users', $users);
            // On récupère la Query à partir du QueryBuilder
            $query = $queryBuilder->getQuery();
            // On récupère les résultats à partir de la Query
            $results = $query->getResult();


            return $results;
        }else{
            $queryBuilder = $this
                ->createQueryBuilder('i')
                ->innerJoin('i.users', 'u')
                ->where('u.id = :users')
                ->andWhere('i.dateRecharge BETWEEN :from AND :to')
                ->setParameters([
                    'users' => $users,
                    'from' => $from,
                    'to' => $to
                ]);
            // On récupère la Query à partir du QueryBuilder
            $query = $queryBuilder->getQuery();
            // On récupère les résultats à partir de la Query
            $results = $query->getResult();


            return $results;

        }

    }
}
